export const footerWrapper = {
  //   borderRadius: "40% 40% 0 0",
  //   position: "relative",
  //   pt: 10,
  //   "&::before": {
  //     position: "absolute",
  //     top: "20px",
  //     left: "50%",
  //     content: "''",
  //     width: "30px",
  //     height: "30px",
  //     borderRadius: "50%",
  //     backgroundColor: "#e5f1f9",
  //     transform: "translate(-15px, 0px)",
  //     border: "5px solid #012F6C",
  //     zIndex: "2",
  //     opacity: "0.8",
  //     // backgroundImage: "url('src/assets/logos/splash-logo-w.png')",
  //     // backgroundRepeat: "no-repeat",
  //     // backgroundSize: "100% auto",
  //   },
  //   "&::after": {
  //     position: "absolute",
  //     zIndex: "1",
  //     top: "20px",
  //     left: "50%",
  //     content: "''",
  //     width: "150px",
  //     opacity: "0.8",
  //     height: "1px",
  //     borderBottom: "1px solid #e5f1f9",
  //     transform: "translate(-75px, 16px)",
  //   },
};
